### ISSUE TITLE
[Bug] Creating save file on the REPL page gives error

### ISSUE THREAD

**Issue by TraceEntertains** [frissyn/berrydeck#1]
Like the title says, creating a save file on the linked REPL for the project gives this error:
![image](https://user-images.githubusercontent.com/73800394/205344425-40437a8f-9704-4c49-9b78-cb733ff6154c.png)

**Comment by TraceEntertains** [comment]
This happens for all save file types as well, with the exact same error. Opening a save file, however, works just fine.

**Comment by frissyn** [comment]
I'm actually working on changes to the BerryDeck application right now. I'm reworking how savefiles are represened internally, so the parser isn't working now. I'll let you know when every becomes usuable again, thanks for trying it out!

**Comment by frissyn** [comment]
The presets are just a placeholder for now as well. I'll add them when I'm done with some other internal work.
