### ISSUE TITLE
Is this actually mentioned or am I just stupid?

### ISSUE THREAD

**Issue by CkreaM** [frissyn/berrydeck#2]
I can't download the save file

**Comment by CkreaM** [comment]
I'm using game version 1.4.0.0

**Comment by frissyn** [comment]
@Nardeem BerryDeck isn't in a usable state as of right now. The backend process of modifying savefile fields is being reworked and I haven't completed it yet. Sorry

**Comment by CkreaM** [comment]
Oh ok, thanks though, excited to see when it's finished!

**Comment by FrozzenAxe** [comment]
Yes! Really looking forward to seeing this working. Currently trying to recreate my switch save so i can continue on my steam deck
